### PR TITLE
Reconstruct ISO10646-1-pl.fon

### PR DESCRIPTION
**Pull request by AnHardt**
from comments in utf_mapper.h

Untested!

### CODE REVIEW

**Comment by Bob-the-Kuhn** [comment]
How about adding the BDF for 6x9?  https://www.dropbox.com/s/aiboqlum2vbk4sn/6x9.bdf?dl=0

**Comment by AnHardt** [comment]
In case you want to stay with the current utf8 system it will be much easier to use my fonts - they have the glyphs at the place the current utf-mapper expects them.
In case you want to use the u8g2 utf-system you have to use a different font source anyway.

At the moment I don't intend to make this PR against MarlinFirmware. So feel free to use the font or not.

**Comment by Bob-the-Kuhn** [comment]
That went over my head. 

It sounds like:
1. The 6x9 BDF I used doesn't conform to the current Marlin system.
2. The current Marlin system is different than the U8G2 system.  To me that means we should be seriously considering moving to the U8G2 system.
3. If Marlin decides to move to U8G2 then we'll need to get on the team someone who knows a lot more about this subject than me.

I've opened Issue #8008 to discuss if Marlin 2.0.x should move to U8G2.  I think it's best to wait until that comes to a conclusion before putting in anymore work on the fonts & mapper.

**Comment by AnHardt** [comment]
1.) Yes. It has only identical glyphs for the  first 255 symbols, to  ISO10646-1. Most west european languages (including english) use this one. So you may not have noticed the differences for other languages.
The marlin fonts have never more then 255 symbols - its a limitation of u8g. (Don't know about u8g²). Even if the number of glyphs is unlimited in u8g² it would not be wise to use that, because of the memory usage. So making font.h files for the used codepages of the language may be better. 
Next problem is the source bdf-file. The one u used, for example, does not contain any chinese characters. That is no wonder. These glyphs can't be drawn in a readable manner in 6x8 pixel. I did not check what is in and what not - but chinese was obvious.
2.) Yes. And no. UTF8 is about the strongest argument for u8g², but also the most time consuming. 
3.) It would be helpful to have someone with knowledge about the fonts. And sorry i'm not your candidate. Bought a house. I'm renovating it myself - mostly. Moved to there - including the company. Keep the business running. Much to much to do for me. Maybe things have settled next year a bit. No chance to ever invest that much time like in 2015-16 again.

**Comment by Bob-the-Kuhn** [comment]
Good luck on the renovation.

I've got a bathroom that's down to the studs.  I need to put some serious time into it soon or the wife will be VERY unhappy.

**Pull request closed without merging**
