### PR TITLE
Delta menu clip

### PR DESCRIPTION
**Pull request by AnHardt**

### CODE REVIEW

**Comment by clefranc** [comment]
Why `DELTA_CLIP_RADIUS` only in the kossel mini configuration file example? What will happen if you use the generic one, or the other delta config?

**Comment by AnHardt** [comment]
Because i was lazy and tired and had the second beer. (about 3am)
Mini Kossel was selected to satisfy Travis. There the Mini Kossel configuration is the only tested delta configuration.
Nothing special will happen - except it will work then for the configurations too.

Until now i'm only playing around, to see how the different ideas come out and how the acceptance will be. Painting the complete picture is an other story.

For me exchanging code with other people is much more convenient when done via a public branch.

**Comment by clefranc** [comment]
Only 2 beers at 3am, you seem to be a reasonable man!

**Comment by AnHardt** [comment]
The second has been to much - forgot to commit the already corrected return.

**Pull request closed without merging**
