### PR TITLE
Add_some_position_reorts_DEBUG

### PR DESCRIPTION
**Pull request by AnHardt**
Please execute:
G28
M111 S255
-- cut log here
G29
-- cut log after the first "<<< probe_pt"

Post log and Configuration.h

### CODE REVIEW

**Comment by alitai** [comment]
@AnHardt Sorry for not realizing how to use this code - just ran it per the instructions (thank you Scott)
[Configuration.h.txt](https://github.com/AnHardt/Marlin/files/362596/Configuration.h.txt)

. The log:

> > > gcode_G29
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > G29 Auto Bed Leveling
> > > reset_bed_level
> > > current_position=(0.00, 0.00, 243.70) : setup_for_endstop_or_probe_move
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > current_position=(0.00, 0.00, 243.70) : set_probe_deployed
> > > deploy: 1X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > do_probe_raise(50.00)
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > do_blocking_move_to(0.00, 0.00, 243.70)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
> > > destination=(0.00, 0.00, 243.70) : prepare_move_to_destination_raw
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > probe_pt(31.00, -49.00, 1)
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > do_probe_raise(5.00)
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > do_blocking_move_to_xy(31.00, -49.00)
> > > X:0.00 Y:0.00 Z:243.70 E:0.00 Count X: 86168 Y:86168 Z:86168
> > > do_blocking_move_to(31.00, -49.00, 243.70)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
> > > X:31.00 Y:-49.00 Z:243.70 E:0.00 Count X: 86168 Y:86248 Z:85995
> > > current_position=(31.00, -49.00, 243.70) : set_probe_deployed
> > > deploy: 1X:31.00 Y:-49.00 Z:243.70 E:0.00 Count X: 86168 Y:86248 Z:85995
> > > current_position=(31.00, -49.00, 243.70) : run_z_probe (DELTA) 1
> > > destination=(31.00, -49.00, -10.00) : prepare_move_to_destination_raw
> > > N43 M105_16
> > > N44 M105_23
> > > N45 M105*22
> > > current_position=(31.00, -49.00, 0.29) : run_z_probe (DELTA) 2
> > > current_position=(31.00, -49.00, 0.29) : sync_plan_position_delta
> > > X:31.00 Y:-49.00 Z:0.29 E:0.00 Count X: 35365 Y:41304 Z:29238
> > > do_probe_raise
> > > do_probe_raise(5.00)
> > > do_blocking_move_to(31.00, -49.00, 5.00)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
> > > destination=(31.00, -49.00, 5.00) : prepare_move_to_destination_raw
> > > <<< probe_pt

**Comment by alitai** [comment]
When the log states - X:31.00 Y:-49.00 Z:0.29 E:0.00  - it is actually at X=0 and Y=0 (bed center..). 

The real X=31 Y=-49 is actually close to the edge of the bed (midway between towers).

**Comment by AnHardt** [comment]
I guess i got it.

> X:31.00 Y:-49.00 Z:243.70 E:0.00 Count X: 86168 Y:86248 Z:85995

is a horizontal move at top level. That is impossible. It's hitting the endstops.

Please alter the test sequence to:

Please execute:
G28
M111 S255
-- cut log here
G0 Z100
G29
-- cut log after the first "<<< probe_pt"

**Comment by alitai** [comment]
Got it. Moving the Z to 100 allowed the XY to move. 

It worked and finished an entire G29 sequence. 

Thank you and kudos for the troubleshooting. Much appreciated.

**Comment by alitai** [comment]
Log:
01:58:42.704 : N844 M105_47
01:58:42.717 : echo:N844 M105_47
01:58:45.764 : N845 M105_46
01:58:45.774 : echo:N845 M105_46
01:58:48.829 : N846 M105_45
01:58:48.846 : echo:N846 M105_45
01:58:51.889 : N847 M105_44
01:58:51.901 : echo:N847 M105_44
01:58:54.955 : N848 M105_35
01:58:54.957 : echo:N848 M105_35
01:58:58.015 : N849 M105_34
01:58:58.029 : echo:N849 M105_34
01:59:01.080 : N850 M105_42
01:59:01.085 : echo:N850 M105_42
01:59:01.450 : N851 G0 Z100_110
01:59:01.454 : echo:N851 G0 Z100_110
01:59:04.138 : N852 M105_40
01:59:07.200 : N853 M105_41
01:59:10.264 : N854 M105_46
01:59:11.340 : echo:N852 M105_40
01:59:11.340 : echo:N853 M105_41
01:59:11.341 : echo:N854 M105_46
01:59:13.331 : N855 M105_47
01:59:13.340 : echo:N855 M105_47
01:59:16.389 : N856 M105_44
01:59:16.395 : echo:N856 M105_44
01:59:16.833 : N857 G29_24
01:59:16.913 : echo:N857 G29_24
01:59:16.913 : >>> gcode_G29
01:59:16.913 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.913 : G29 Auto Bed Leveling
01:59:16.913 : reset_bed_level
01:59:16.913 : current_position=(0.00, 0.00, 100.00) : setup_for_endstop_or_probe_move
01:59:16.913 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.913 : current_position=(0.00, 0.00, 100.00) : set_probe_deployed
01:59:16.913 : deploy: 1X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.913 : do_probe_raise(50.00)
01:59:16.913 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.913 : do_blocking_move_to(0.00, 0.00, 100.00)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
01:59:16.914 : destination=(0.00, 0.00, 100.00) : prepare_move_to_destination_raw
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : >>> probe_pt(31.00, -49.00, 1)
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : do_probe_raise(5.00)
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : > do_blocking_move_to_xy(31.00, -49.00)
01:59:16.914 : X:0.00 Y:0.00 Z:100.00 E:0.00 Count X: 57428 Y:57428 Z:57428
01:59:16.914 : do_blocking_move_to(31.00, -49.00, 100.00)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
01:59:17.993 : X:31.00 Y:-49.00 Z:100.00 E:0.00 Count X: 55306 Y:61245 Z:49179
01:59:17.993 : > current_position=(31.00, -49.00, 100.00) : set_probe_deployed
01:59:17.993 : deploy: 1X:31.00 Y:-49.00 Z:100.00 E:0.00 Count X: 55306 Y:61245 Z:49179
01:59:17.993 : current_position=(31.00, -49.00, 100.00) : run_z_probe (DELTA) 1
01:59:17.993 : destination=(31.00, -49.00, -10.00) : prepare_move_to_destination_raw
01:59:19.456 : N858 M105*34
01:59:21.497 : current_position=(31.00, -49.00, 0.14) : run_z_probe (DELTA) 2
01:59:21.497 : current_position=(31.00, -49.00, 0.14) : sync_plan_position_delta
01:59:21.497 : X:31.00 Y:-49.00 Z:0.14 E:0.00 Count X: 35334 Y:41274 Z:29208
01:59:21.497 : > do_probe_raise
01:59:21.497 : do_probe_raise(5.00)
01:59:21.497 : do_blocking_move_to(31.00, -49.00, 5.00)SOURCE_CODE_URL:https://github.com/MarlinFirmware/Marlin PROTOCOL_VERSION:1.0 MACHINE_TYPE:Mini Kossel EXTRUDER_COUNT:1 UUID:cede2a2f-41a2-4748-9b12-c55c62f367ff
01:59:21.498 : destination=(31.00, -49.00, 5.00) : prepare_move_to_destination_raw
01:59:21.625 : <<< probe_pt

**Pull request closed without merging**
